const express = require('express');
const route = express.Router();
const productsController = require('../app/controllers/productController.js');
const vnpayReturnController = require('../app/controllers/vnpayReturnController.js');
route.get('/getallproducts', productsController.getallProducts);
route.get('/searchproducts', productsController.searchProducts);
route.get('/getproductbyid', productsController.getProductById);
route.get('/getproductbycategory', productsController.getProductsByCategory);
route.get('/getcarts', productsController.getCarts);
route.get('/fetchGroupedByShop', productsController.fetchProductsByShopGrouped);
route.post('/creatpaymenturl', vnpayReturnController.createPaymentUrl);
route.post('/addtocart', productsController.addtoCarts);
route.post('/deletetocart', productsController.removeFromCart);
route.get('/fetchbyShop', productsController.getProductsByShop);
route.post('/create', productsController.createProduct);
route.put('/update/:id', productsController.updateProduct);
route.delete('/delete/:id', productsController.deleteProduct);
module.exports = route;
